name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.4"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.4"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
          pytest --cov=. --cov-fail-under=80

  quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.4"
      - name: Install linter
        run: |
          pip install flake8
      - name: Run flake8
        run: flake8 .

  package:
    runs-on: ubuntu-latest
    needs: [test, quality]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
  
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/matthieu-chambon/oc_projet_13/django-app:latest .
  
      - name: Push Docker image
        run: |
          docker push ghcr.io/matthieu-chambon/oc_projet_13/django-app:latest
